/**
 * Checks to see if the find command returns a 'BadValue' error when the $size
 * operator is given a non-negative number.
 */

(function() {
  'use strict';
  const assert = require('assert');
  const coll = db.issue1539;

  coll.drop();

  docs = [
    {_id: 'double', v: 42.13},
    {_id: 'double-whole', v: 42.0},
    {_id: 'double-zero', v: 0.0},
    {_id: 'double-max', v: Number.MAX_VALUE},
    {_id: 'double-smallest', v: Number.MIN_VALUE},
    {_id: 'doubleBig', v: Number(2 << 60)},
    {_id: 'double-null', v: null},
  ];

  coll.insertMany(docs);

  const expectedErrorCode = 2;

  const process = db.serverStatus().process;
  const version = db.serverStatus().version;
  console.log(process, version);

  let x = {v: {$size: -1}};
  try {
    coll.findOne(x);
  } catch (error) {
    assert.equal(error.code, expectedErrorCode);
    console.log('issue1539 passed')
    return;
  }
  console.log('issue1539 failed');
})();
